version: '3'

services:
  reverse-proxy:
    image: nginx:alpine
    container_name: reverse-proxy
    network_mode: "host"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
